// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID          int32
	Name        string
	Email       string
	CreatedAt   pgtype.Timestamp
	AdminStatus pgtype.Text
}

type Merchant struct {
	ID        int32
	Name      string
	Email     string
	PartnerID string
	CreatedAt pgtype.Timestamp
}

type Partner struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
	Status    pgtype.Text
	Username  pgtype.Text
}

type Payout struct {
	ID                int32
	Crn               pgtype.Int4
	AccountNumber     string
	TransactionStatus string
	CreatedAt         pgtype.Timestamp
}

type StatusCheck struct {
	ID                int32
	Crn               pgtype.Int4
	AccountNumber     string
	TransactionStatus string
	CreatedAt         pgtype.Timestamp
}
